import React, { useState } from 'react';
import { View, Text, StyleSheet, TextInput, TouchableOpacity, ScrollView } from 'react-native';
import { colors } from '../theme/colors';
import { chatWithSidekick, transcribeAudio } from '../lib/api';
import { recordAudio } from '../lib/audio';
export default function Chat(){ const [input,setInput]=useState(''); const [log,setLog]=useState<string[]>([]);
async function send(){ const msg=input.trim(); if(!msg) return; setLog(l=>[...l, `You: ${msg}`]); setInput(''); const res = await chatWithSidekick(msg); setLog(l=>[...l, `Takoda: ${res}`]); }
async function capture(){ setLog(l=>[...l, 'Recording up to 4s...']); const uri = await recordAudio(4000); if(!uri){ setLog(l=>[...l, 'Recording failed.']); return; } const text = await transcribeAudio(uri); setLog(l=>[...l, `Spark: ${text}`]); }
return (<View style={s.c}><ScrollView style={s.log}>{log.map((l,i)=>(<Text key={i} style={s.line}>{l}</Text>))}</ScrollView><View style={s.row}><TouchableOpacity onPress={capture} style={s.btnAlt}><Text style={s.btnAltText}>Voice</Text></TouchableOpacity><TextInput style={s.input} value={input} onChangeText={setInput} placeholder='Ask your sidekick...' placeholderTextColor={colors.textDim} onSubmitEditing={send} /><TouchableOpacity onPress={send} style={s.btn}><Text style={s.btnText}>Send</Text></TouchableOpacity></View></View>); }
const s = StyleSheet.create({ c:{ flex:1, backgroundColor: colors.bg, padding:12 }, log:{ flex:1 }, line:{ color: colors.text, marginVertical:4 }, row:{ flexDirection:'row', alignItems:'center' }, input:{ flex:1, backgroundColor:'#0f1e16', borderColor: colors.accent, borderWidth:1, color: colors.text, borderRadius:10, paddingHorizontal:12, height:44, marginHorizontal:8 }, btn:{ backgroundColor: colors.accent, borderRadius:10, paddingHorizontal:16, height:44, alignItems:'center', justifyContent:'center' }, btnText:{ color: colors.darkInk, fontWeight:'900' }, btnAlt:{ backgroundColor:'#113a28', borderRadius:10, paddingHorizontal:12, height:44, alignItems:'center', justifyContent:'center' }, btnAltText:{ color: colors.text } });